### ISSUE TITLE
Support snforge 0.19 – install universal-sierra-compiler correctly

### ISSUE THREAD

**Issue by tensojka** [foundry-rs/setup-snfoundry#21]
`Cannot find `universal-sierra-compiler` binary. Make sure you have USC installed https://github.com/software-mansion/universal-sierra-compiler and added to PATH (or set at UNIVERSAL_SIERRA_COMPILER env var): cannot find binary path`

https://github.com/CarmineOptions/governance/actions/runs/8299664916/job/22715883695

**Comment by drknzz** [comment]
Hey @tensojka
I see you're using `foundry-rs/setup-snfoundry@v2`, but a new `v3` version [came out recently](https://github.com/foundry-rs/setup-snfoundry/releases). Could you check if the issue persists after the change?

**Comment by tensojka** [comment]
Now it works. I simply used the snippet from README, so I suggest updating it there. Thanks
