### ISSUE TITLE
Support fetching version from `.tool-versions`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/setup-snfoundry#8]
In case the version of the tool is not defined and the `.tool-versions` file from asdf is present, we should use version defined there instead of "latest".

**Comment by julio4** [comment]
This is a useful feature! Scarb already implement this (see [versions.js](https://github.com/software-mansion/setup-scarb/blob/main/lib/versions.js))

**Comment by cptartur** [comment]
We want to do it eventually, but we're currently focused on topics in the Starknet Foundry itself. PRs are welcome though 😅

**Comment by Arcticae** [comment]
Done in #18
